apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8-lint
spec:
  description: Run flake8 on Python source code
  workspaces:
    - name: output
  params:
    - name: image
      type: string
      default: "python:3.9-slim"
    - name: flags
      type: string
      default: "--count --max-complexity=10 --max-line-length=127 --statistics"
  steps:
    - name: flake8
      image: $(params.image)
      workingDir: $(workspaces.output.path)
      script: |
        #!/bin/sh
        set -e
        pip install flake8
        flake8 $(params.flags) .