tasks:
  - name: clone
    workspaces:
      - name: output
        workspace: pipeline-workspace
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.branch)

  - name: lint
    workspaces:
      - name: output
        workspace: pipeline-workspace
    taskRef:
      name: flake8-lint
    params:
      - name: args
        value: ["--count","--max-complexity=10","--max-line-length=127","--statistics"]
    runAfter:
      - clone

  - name: tests
    workspaces:
      - name: source
        workspace: pipeline-workspace
    taskRef:
      name: nose
    params:
  - name: database_uri
    value: "sqlite:///test.db"
  - name: args
    value: "-v --with-spec --spec-color"
    runAfter:
      - clone
